import React, { useCallback, useEffect, useState } from 'react';
import {
  ActivityIndicator,
  Alert,
  KeyboardAvoidingView,
  NativeScrollEvent,
  NativeSyntheticEvent,
  Platform,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  View,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import * as WebBrowser from 'expo-web-browser';
import * as Linking from 'expo-linking';
import { useRouter } from 'expo-router';
import * as AppleAuthentication from 'expo-apple-authentication';
import { Check, Hammer, ShieldCheck, ChevronDown } from 'lucide-react-native';
import FadeInView from '@/src/components/FadeInView';
import Button from '@/src/components/Button';
import { useAuth } from '@/src/lib/auth';
import { colors, radius, space, text } from '@/src/lib/theme';

const DISCLAIMER = `PROFESSIONAL SERVICES DISCLAIMER

By using Handy Andy: Job Site Assistant ("the Application"), you acknowledge and accept the following terms in full. Scroll to the bottom to enable the agreement checkbox.

1. NATURE OF SERVICE
The Application provides AI-assisted diagnostics, repair suggestions, bill of materials estimates, and field-safety evaluations. All output is generated by predictive models and computer-vision analysis. It is informational guidance, not a substitute for inspection by a licensed professional.

2. NO PROFESSIONAL ADVICE
Nothing in the Application constitutes legal, engineering, electrical, plumbing, structural, or code-compliance advice. Users must independently verify all recommendations against local building codes, manufacturer specifications, and applicable jurisdictional regulations before performing any work.

3. SAFETY ACKNOWLEDGEMENT
Field work involves inherent risk including, without limitation, electrical shock, fire, mechanical injury, falls from elevation, chemical exposure, and structural collapse. You agree to follow lockout/tagout procedures, wear appropriate personal protective equipment, and disengage from any task that exceeds your training or licensure.

4. ARTIFICIAL INTELLIGENCE LIMITATIONS
AI vision analysis can misidentify components, miss hidden defects, and produce incorrect bill-of-materials suggestions. Treat all AI output as a starting point — verify on-site with the appropriate test instruments before purchasing parts or executing repairs.

5. SUPPLY CHAIN AND PRICING
Inventory indicators (In Stock, Low Stock, Out of Stock) are estimates derived from mock supplier feeds for demonstration purposes. Confirm availability and pricing directly with your distributor.

6. DATA HANDLING
Photographs you capture or upload are transmitted to AI vision providers for processing. Do not upload images containing confidential customer information, identifiable persons without consent, or hazardous personally-identifiable material.

7. LIMITATION OF LIABILITY
To the maximum extent permitted by law, the Application's providers shall not be liable for any direct, indirect, incidental, consequential, or punitive damages arising from your use of the Application, including property damage, code violations, or personal injury.

8. INDEMNIFICATION
You agree to indemnify and hold harmless the Application's owners, operators, and affiliates against any claims arising from your use of AI-generated recommendations in the field.

9. ACCEPTANCE
By tapping the agreement checkbox below and proceeding, you acknowledge that you have read, understood, and agree to these terms in their entirety. If you do not agree, do not use the Application.

— END OF DISCLAIMER —`;

WebBrowser.maybeCompleteAuthSession();

export default function LoginScreen() {
  const { user, signInDev, consumeSessionToken } = useAuth();
  const router = useRouter();
  const [scrolledToBottom, setScrolledToBottom] = useState(false);
  const [agreed, setAgreed] = useState(false);
  const [email, setEmail] = useState('');
  const [loadingGoogle, setLoadingGoogle] = useState(false);
  const [loadingDev, setLoadingDev] = useState(false);
  const [loadingApple, setLoadingApple] = useState(false);
  const [appleAvailable, setAppleAvailable] = useState(false);

  useEffect(() => {
    if (Platform.OS !== 'ios') { setAppleAvailable(false); return; }
    AppleAuthentication.isAvailableAsync().then(setAppleAvailable).catch(() => setAppleAvailable(false));
  }, []);

  useEffect(() => {
    if (user) router.replace('/(tabs)');
  }, [user, router]);

  // Cold start handler for OAuth redirect (mobile)
  useEffect(() => {
    if (Platform.OS === 'web') return;
    const sub = Linking.addEventListener('url', ({ url }) => handleRedirect(url));
    Linking.getInitialURL().then((u) => u && handleRedirect(u));
    return () => sub.remove();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleRedirect = useCallback(async (url: string) => {
    const m = url.match(/[#?]session_id=([^&]+)/);
    if (!m) return;
    try {
      await consumeSessionToken(decodeURIComponent(m[1]));
      router.replace('/(tabs)');
    } catch (e: any) {
      Alert.alert('Sign-in failed', e?.message || 'Could not validate session');
    }
  }, [consumeSessionToken, router]);

  const onScroll = (e: NativeSyntheticEvent<NativeScrollEvent>) => {
    const { layoutMeasurement, contentOffset, contentSize } = e.nativeEvent;
    const padding = 20;
    if (contentOffset.y + layoutMeasurement.height >= contentSize.height - padding) {
      if (!scrolledToBottom) setScrolledToBottom(true);
    }
  };

  const onGoogleSignIn = async () => {
    if (!agreed) return;
    setLoadingGoogle(true);
    try {
      const redirectUrl = Linking.createURL('auth');
      const authUrl = `https://auth.emergentagent.com/?redirect=${encodeURIComponent(redirectUrl)}`;
      // Google OAuth policy (RFC 8252): MUST use the system browser, not a WebView.
      // `openAuthSessionAsync` uses ASWebAuthenticationSession on iOS and Chrome
      // Custom Tabs on Android — both Google-approved secure user-agents.
      const result = await WebBrowser.openAuthSessionAsync(authUrl, redirectUrl, {
        preferEphemeralSession: true, // iOS: no shared cookies, private session
        showInRecents: false,         // Android: don't surface auth URL in recents
      });
      if (result.type === 'success' && result.url) {
        await handleRedirect(result.url);
      }
    } catch (e: any) {
      Alert.alert('Sign-in error', e?.message || 'OAuth failed');
    } finally {
      setLoadingGoogle(false);
    }
  };

  const onDevSignIn = async () => {
    if (!agreed) return;
    const target = email.trim() || 'tester@jphandy.dev';
    setLoadingDev(true);
    try {
      await signInDev(target, target.split('@')[0]);
      router.replace('/(tabs)');
    } catch (e: any) {
      Alert.alert('Login failed', e?.message || 'Try again');
    } finally {
      setLoadingDev(false);
    }
  };

  return (
    <SafeAreaView style={styles.safe} edges={['top', 'bottom']}>
      <KeyboardAvoidingView
        behavior={Platform.OS === 'ios' ? 'padding' : undefined}
        style={{ flex: 1 }}
      >
        <View style={styles.header}>
          <View style={styles.brandRow}>
            <Hammer size={36} color={colors.primary} strokeWidth={2.5} />
            <View>
              <Text style={styles.brand}>HANDY ANDY</Text>
              <Text style={styles.tag}>JOB SITE ASSISTANT</Text>
            </View>
          </View>
          <View style={styles.barRow}>
            <View style={[styles.stripe, { backgroundColor: colors.primary }]} />
            <View style={[styles.stripe, { backgroundColor: '#0a0a0a' }]} />
            <View style={[styles.stripe, { backgroundColor: colors.primary }]} />
            <View style={[styles.stripe, { backgroundColor: '#0a0a0a' }]} />
          </View>
        </View>

        <View style={styles.disclaimerCard}>
          <View style={styles.disclaimerHead}>
            <ShieldCheck size={16} color={colors.primary} />
            <Text style={styles.disclaimerTitle}>SERVICES DISCLAIMER</Text>
            {!scrolledToBottom && (
              <View style={styles.scrollHint}>
                <Text style={styles.scrollHintText}>SCROLL TO END</Text>
                <ChevronDown size={12} color={colors.primary} />
              </View>
            )}
          </View>
          <ScrollView
            testID="disclaimer-scroll"
            style={styles.disclaimerScroll}
            onScroll={onScroll}
            scrollEventThrottle={80}
            showsVerticalScrollIndicator
          >
            <Text style={styles.disclaimerText}>{DISCLAIMER}</Text>
          </ScrollView>
        </View>

        <Pressable
          testID="login-agree-checkbox"
          disabled={!scrolledToBottom}
          onPress={() => setAgreed((a) => !a)}
          style={[styles.agreeRow, !scrolledToBottom && { opacity: 0.45 }]}
          accessible
          accessibilityRole="checkbox"
          accessibilityLabel="I agree to the Professional Services Disclaimer"
          accessibilityHint={scrolledToBottom ? 'Activates after you scroll to the end of the disclaimer above' : 'Scroll the disclaimer to the bottom to enable this control'}
          accessibilityState={{ checked: agreed, disabled: !scrolledToBottom }}
          hitSlop={{ top: 12, bottom: 12, left: 12, right: 12 }}
        >
          <View
            style={[
              styles.checkbox,
              agreed && { backgroundColor: colors.primary, borderColor: colors.primary },
            ]}
          >
            {agreed && <Check size={16} color="#0a0a0a" strokeWidth={3.5} />}
          </View>
          <Text style={styles.agreeText}>
            I have read and agree to the terms of the disclaimer above.
          </Text>
        </Pressable>

        <View style={styles.actions}>
          <FadeInView
            from={{ opacity: 0, translateY: 12 }}
            animate={{ opacity: 1, translateY: 0 }}
            transition={{ type: 'timing', duration: 350 }}
          >
            <Button
              testID="login-google-btn"
              label={loadingGoogle ? 'CONNECTING…' : 'SIGN IN WITH GOOGLE'}
              variant="primary"
              disabled={!agreed || loadingGoogle}
              loading={loadingGoogle}
              onPress={onGoogleSignIn}
              fullWidth
            />
          </FadeInView>

          {appleAvailable && (
            <AppleAuthentication.AppleAuthenticationButton
              testID="login-apple-btn"
              buttonType={AppleAuthentication.AppleAuthenticationButtonType.SIGN_IN}
              buttonStyle={AppleAuthentication.AppleAuthenticationButtonStyle.WHITE}
              cornerRadius={4}
              style={{ height: 50, opacity: agreed && !loadingApple ? 1 : 0.4 }}
              onPress={async () => {
                if (!agreed || loadingApple) return;
                setLoadingApple(true);
                try {
                  const cred = await AppleAuthentication.signInAsync({
                    requestedScopes: [
                      AppleAuthentication.AppleAuthenticationScope.FULL_NAME,
                      AppleAuthentication.AppleAuthenticationScope.EMAIL,
                    ],
                  });
                  if (cred.identityToken) {
                    const fn = cred.fullName ? `${cred.fullName.givenName || ''} ${cred.fullName.familyName || ''}`.trim() : undefined;
                    const { api: apiClient } = await import('@/src/lib/api');
                    const r = await apiClient.appleLogin(cred.identityToken, fn, cred.email || undefined);
                    await consumeSessionToken(r.session_token);
                    router.replace('/(tabs)');
                  }
                } catch (e: any) {
                  if (e?.code !== 'ERR_REQUEST_CANCELED') Alert.alert('Apple Sign-In failed', e?.message || '');
                } finally { setLoadingApple(false); }
              }}
            />
          )}

          <View style={styles.divider}>
            <View style={styles.dividerLine} />
            <Text style={styles.dividerText}>OR DEV LOGIN</Text>
            <View style={styles.dividerLine} />
          </View>

          <TextInput
            testID="login-email-input"
            value={email}
            onChangeText={setEmail}
            placeholder="tester@jphandy.dev"
            placeholderTextColor={colors.textTertiary}
            autoCapitalize="none"
            keyboardType="email-address"
            style={styles.input}
            editable={agreed && !loadingDev}
          />
          <Button
            testID="login-dev-btn"
            label={loadingDev ? 'SIGNING IN…' : 'CONTINUE'}
            variant="outline"
            disabled={!agreed || loadingDev}
            loading={loadingDev}
            onPress={onDevSignIn}
            fullWidth
          />
        </View>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  header: {
    paddingHorizontal: space.lg,
    paddingTop: space.md,
    paddingBottom: space.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  brandRow: { flexDirection: 'row', alignItems: 'center', gap: space.md },
  brand: { color: colors.primary, fontSize: 28, fontWeight: '900', letterSpacing: 4 },
  tag: { color: colors.textSecondary, fontSize: 10, fontWeight: '700', letterSpacing: 2 },
  barRow: { flexDirection: 'row', marginTop: space.md, gap: 2 },
  stripe: { flex: 1, height: 4, borderRadius: 1 },
  disclaimerCard: {
    margin: space.lg,
    marginBottom: space.md,
    borderWidth: 2,
    borderColor: colors.borderStrong,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    flex: 1,
    overflow: 'hidden',
  },
  disclaimerHead: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: space.sm,
    paddingHorizontal: space.md,
    paddingVertical: space.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderStrong,
    backgroundColor: colors.surfaceElevated,
  },
  disclaimerTitle: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 1.5,
    flex: 1,
  },
  scrollHint: { flexDirection: 'row', alignItems: 'center', gap: 2 },
  scrollHintText: { color: colors.primary, fontSize: 10, fontWeight: '900', letterSpacing: 1 },
  disclaimerScroll: { padding: space.md },
  disclaimerText: { color: colors.textSecondary, fontSize: 13, lineHeight: 20 },
  agreeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: space.lg,
    paddingVertical: space.sm,
    gap: space.md,
  },
  checkbox: {
    width: 26,
    height: 26,
    borderWidth: 2,
    borderColor: colors.borderStrong,
    borderRadius: radius.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  agreeText: { color: colors.textPrimary, fontSize: 13, flex: 1, fontWeight: '600' },
  actions: { paddingHorizontal: space.lg, paddingBottom: space.lg, gap: space.md },
  divider: { flexDirection: 'row', alignItems: 'center', gap: space.sm },
  dividerLine: { flex: 1, height: 1, backgroundColor: colors.border },
  dividerText: { color: colors.textTertiary, fontSize: 10, fontWeight: '900', letterSpacing: 1.5 },
  input: {
    backgroundColor: colors.background,
    borderWidth: 2,
    borderColor: colors.borderStrong,
    borderRadius: radius.sm,
    padding: space.md,
    color: colors.textPrimary,
    fontSize: 14,
  },
});
