import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { ChevronLeft, FileText } from 'lucide-react-native';
import { colors, radius, space } from '@/src/lib/theme';

export const TERMS_VERSION = '1.0.0';

const TERMS = `# Terms of Service — Professional Services Disclaimer

Effective 2026-02-01 · Version 1.0.0

By using Handy-Andy: Job Site Assistant ("the Application") you acknowledge and accept the following terms in full.

1. NATURE OF SERVICE
The Application provides AI-assisted diagnostics, repair suggestions, bill of materials estimates, and field-safety evaluations. All output is generated by predictive models and computer-vision analysis. It is informational guidance, not a substitute for inspection by a licensed professional.

2. NO PROFESSIONAL ADVICE
Nothing in the Application constitutes legal, engineering, electrical, plumbing, structural, or code-compliance advice. Users must independently verify all recommendations against local building codes, manufacturer specifications, and applicable jurisdictional regulations before performing any work.

3. SAFETY ACKNOWLEDGEMENT
Field work involves inherent risk including, without limitation, electrical shock, fire, mechanical injury, falls from elevation, chemical exposure, and structural collapse. You agree to follow lockout/tagout procedures, wear appropriate personal protective equipment, and disengage from any task that exceeds your training or licensure.

4. ARTIFICIAL INTELLIGENCE LIMITATIONS
AI vision analysis can misidentify components, miss hidden defects, and produce incorrect bill-of-materials suggestions. Treat all AI output as a starting point — verify on-site with the appropriate test instruments before purchasing parts or executing repairs.

5. SUPPLY CHAIN AND PRICING
Inventory indicators (In Stock, Low Stock, Out of Stock) are estimates derived from mock supplier feeds for demonstration purposes. Confirm availability and pricing directly with your distributor.

6. DATA HANDLING
Photographs, voice recordings, and location coordinates that you capture or upload are transmitted to third-party AI vision and transcription providers strictly for processing. Do not upload images containing confidential customer information, identifiable persons without consent, or hazardous personally-identifiable material. See the Privacy Policy for full disclosure.

7. LIMITATION OF LIABILITY
THE APPLICATION IS PROVIDED "AS IS" AND "AS AVAILABLE". TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE APPLICATION'S PROVIDERS SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE APPLICATION, INCLUDING WITHOUT LIMITATION PROPERTY DAMAGE, CODE VIOLATIONS, MISSED CALENDAR EVENTS, BUSINESS INTERRUPTION, DATA LOSS, SCHEDULING HALLUCINATIONS, OR PERSONAL INJURY.

8. INDEMNIFICATION
You agree to indemnify and hold harmless the Application's owners, operators, and affiliates against any claims arising from your use of AI-generated recommendations in the field.

9. SUBSCRIPTION TERMS
Pro tier is $39/month with a 7-day free trial. You may cancel at any time in Settings; cancellation takes effect at the end of the current billing period. No refunds for partial periods.

10. ACCEPTANCE
By tapping the agreement checkbox during onboarding, you acknowledge that you have read, understood, and agree to these terms in their entirety. Continued use of the Application constitutes ongoing acceptance.

— END —
`;

export default function TermsScreen() {
  const router = useRouter();
  return (
    <SafeAreaView style={styles.safe} edges={['top']}>
      <View style={styles.top}>
        <Pressable testID="terms-back" onPress={() => router.back()} style={styles.icon}>
          <ChevronLeft size={22} color={colors.textPrimary} />
        </Pressable>
        <View style={styles.titleBox}>
          <FileText size={16} color={colors.primary} />
          <Text style={styles.title}>TERMS OF SERVICE</Text>
        </View>
        <View style={{ width: 44 }} />
      </View>
      <ScrollView testID="terms-scroll" contentContainerStyle={styles.scroll}>
        <Text style={styles.body}>{TERMS}</Text>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  top: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: space.lg, borderBottomWidth: 1, borderBottomColor: colors.border },
  icon: { width: 44, height: 44, borderRadius: radius.sm, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.borderStrong, backgroundColor: colors.surface },
  titleBox: { flexDirection: 'row', alignItems: 'center', gap: space.sm },
  title: { color: colors.textPrimary, fontWeight: '900', letterSpacing: 1.5 },
  scroll: { padding: space.lg, paddingBottom: space.xxl },
  body: { color: colors.textSecondary, fontSize: 13, lineHeight: 20 },
});
